dl214@soetcse:~/vidya$ python3 32python.py
enter value of a:12
enter value of b:34
what do you want to do? +,-,*,/+
46
dl214@soetcse:~/vidya$ python3 32python.py
enter value of a:34
enter value of b:45
what do you want to do? +,-,*,/-
-11
dl214@soetcse:~/vidya$ python3 32python.py
enter value of a:45
enter value of b:21
what do you want to do? +,-,*,/*
Traceback (most recent call last):
  File "32python.py", line 26, in <module>
    print(res)
NameError: name 'res' is not defined
dl214@soetcse:~/vidya$ python3 32python.py
enter value of a:12
enter value of b:23
what do you want to do? +,-,*,/*
Traceback (most recent call last):
  File "32python.py", line 26, in <module>
    print(res)
NameError: name 'res' is not defined
dl214@soetcse:~/vidya$ python3 32python.py
enter value of a:12
enter value of b:23
what do you want to do? +,-,*,//
0.5217391304347826
dl214@soetcse:~/vidya$ python3 32python.py
enter value of a:12
enter value of b:34
what do you want to do? +,-,*,/x
Traceback (most recent call last):
  File "32python.py", line 26, in <module>
    print(res)
NameError: name 'res' is not defined
dl214@soetcse:~/vidya$ 

